### ISSUE TITLE
Incompatible with ValheimRAFT

### ISSUE THREAD

**Issue by The-Frenchy** [searica/MoreVanillaBuildPrefabs#8] opened 2024-05-20 08:19 UTC
https://thunderstore.io/c/valheim/p/zolantris/ValheimRAFT/

All attempts to build a raft will result in floating parts.

![image](https://github.com/searica/MoreVanillaBuildPrefabs/assets/59771810/2ad932dd-c02c-40dd-b05f-c884680a9e40)

**Comment by searica** [comment] 2024-05-20 14:40
Hey, thanks for opening an issue. This is currently not enough information for me to go off though. Could you please provide a description of what you need to do to reproduce this issue and confirm that the issue does not occur when just using ValheimRAFT by itself?

In the image you have shared it appears to be two pieces that are added by ValheimRAFT, which should not be affect by MoreVanillaBuildPrefabs at all, and there are no pieces from MoreVanillaBuildPrefabs. So I am also unsure why you think this is a compatibility issue. Would you be able to provide an explanation of why you think it is?

**Comment by The-Frenchy** [comment] 2024-05-20 14:52
Hey, it only happens when the two mods are enabled simultaneously.
I know it makes little to no sense but ValheimRAFT works fine by itself.
That's how I got there, just letting you know they don't work together.

I posted the issue on ValheimRAFT end too.

Here are the error logs if it helps :
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimRAFT.Patches.Player_Patch.PlacedPiece (Player player, UnityEngine.GameObject gameObject) (at <29ab4afd77064c2cb94779e0be45d334>:0)
(wrapper dynamic-method) Player.DMD<Player::PlacePiece>(Player,Piece)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Comment by searica** [comment] 2024-05-20 14:56
Okay, good to know. Thanks for confirming it is only when both are installed. I appreciate you sharing the error, would you be able to upload your full log file? After I take a look at it I can also reach out to zolantris to see if we can work out the issue.

**Comment by searica** [comment] 2024-05-20 14:59
Follow up, I cannot reproduce the issue of floating pieces when using both MVBP and RAFT but I do still get that same error in the log file.

![Screenshot 2024-05-20 075810](https://github.com/searica/MoreVanillaBuildPrefabs/assets/143636061/ef6b5d57-4749-4438-b366-4421b9d02609)

**Comment by The-Frenchy** [comment] 2024-05-20 15:21
RAFT doesn't allow you to put multiple wheel, it breaks the previous one, I don't think you'd be able to move the raft as it is.
You can see them float when the raft moves because of the waves.

Full log : https://pastebin.com/GzS3uKMx

**Comment by searica** [comment] 2024-05-20 15:35
Oh, I built the first two wheels without using MVBP and RAFT together, and then the third with MVBP and RAFT together. Wasn't aware the issue had anything to do with when the raft is moving and floating. I dug a bit into the code based on the log file and error that RAFT is throwing and have made a pull request to RAFT to hopefully fix the issue.

**Comment by searica** [comment] 2024-05-22 03:06
zolantris has merged a PR based on the one that I made to resolve the issue https://github.com/zolantris/ValheimMods/pull/83#issue-2307902072 so I'll close this issue.

**Closed as completed by searica** 2024-05-22 03:06 UTC
